############################ Default configuration #########################
baseURL = "https://medicionpsicologica.com/"
languageCode = "es-es"
# site title 
title = "Avances en Medición Psicológica"
# theme
theme = "northendlab-hugo"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "20"
# disqus short name
disqusShortname = "medicionpsicologica" # get your shortname form here : https://disqus.com

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$",
               "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
 
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


########################### Navigation ###################################

# main menu
[[menu.main]]
URL = "contacto"
name = "Contáctanos"
weight = 1

[[menu.main]]
URL = "tools"
name = "Herramientas"
weight = 2

# footer menu
[[menu.footer]]
URL = "contacto"
name = "Contáctanos"
weight = 1

[[menu.footer]]
URL = "tools"
name = "Herramientas"
weight = 2


######################### Default Parameters ###########################
[params]
# home
home = "Inicio"
# logo
logo = "images/Logo-low-size.png"
# meta data
author = "Avances en Medición Psicológica"
description = "AMP es un grupo de estudios de la UNMSM dedicado a la investigación y desarrollo de actividades a favor de la ciencia Psicológica."
# google tag manager
google_tag_manager = "" # your id
# google analitycs ID
google_analitycs_id = "" # your id
# contact form action
contact_form_action = "https://formspree.io/mqklybap" # contact form works with : https://formspree.io
# copyright
copyright = "&copy; 2021 Avances en Medición Psicológica. Por una ciencia libre."

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 30

####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
title = "Bienvenidos a Avances en Medición Psicológica. <br> Un grupo de la UNMSM."
image = "images/banner/illustration.svg"


######################## call to action ###############################
[params.cta]
enable = true
image = "images/ampi-mascota.png"
title = "Nuestras actividades e investigaciones"
description = "Puede encontrar los materiales de nuestras actividades/investigaciones totalmente libres para compartir."
[params.cta.button]
enable = true
label = "¡Entre aquí!"
link = "https://osf.io/rvbpm/"


############################## Social Site ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
link = "https://www.facebook.com/amp.unmsm/"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "https://twitter.com/ge_amp"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/grupoamp/"
[[params.social]]
icon = "ti-youtube" # themify icon pack https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UC7KqLj6zWBuJtklHSbHp4Cg"
